### ISSUE TITLE
Namespaces lose "dynamic" attribute upon exposing.

### ISSUE THREAD

**Issue by greschd** [aiidateam/plumpy#135]
When using ``expose_inputs`` on a workchain with dynamic input namespaces, the namespace becomes non-dynamic in the spec of the "upper" workchain. Minimal example:

```python
class Lower(WorkChain):
    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.input_namespace('foo', dynamic=True)
        
class Upper(WorkChain):
    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.expose_inputs(Lower)

print(Lower.spec().inputs._ports['foo'].dynamic) # True 
print(Upper.spec().inputs._ports['foo'].dynamic) # False
```

AiiDA version : commit 33bd8b10055ac9777eb7a76a00afbfb1cb138699
plumpy version: 0.14.3

**Comment by greschd** [comment]
Actually, should absorbing a ``dynamic=False`` namespace into a ``dynamic=True`` one change the ``dynamic`` attribute of the absorbing namespace? In other words, what should be the result of the following code?

```python
class Lower(WorkChain):
    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.inputs.dynamic = False # just for clarity - this is the default

class Upper(WorkChain):
    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.inputs.dynamic = True
        spec.expose_inputs(Lower)
```

I think it would make sense for that to remain ``dynamic=True``.

**Comment by bosonie** [comment]
Dear @greschd 
I keep bumping into this problem, so I guess it's time to ask if we have any news about it. As simple user, I would like that the exposed inputs maintain the dynamic attribute defined in the Lower level WorkChain. Is this difficult to have? I just would like an update as this problem is somehow limiting me.

**Comment by greschd** [comment]
I don't think it's difficult to implement, but I'd like to get input from @sphuber whether he agrees on what the desired behavior is.

**Comment by greschd** [comment]
As a temporary workaround, you can (re-)set the `dynamic` attribute after the exposing call. It's a bit annoying, but the best solution you can use immediately.

**Comment by sphuber** [comment]
@greschd is right that the problem is due to the fact that in `absorb` all attributes of the target class are overloaded to the exposing class. Since `valid_type` is set after `dynamic`, if that is `None`, the setter logic in `valid_type` will reset `dynamic` back to `False`. I originally implemented this logic such that when someone sets `valid_type` to a certain type, `dynamic` would be automatically set to `True`, which is the only thing that makes sense. However, this logic seems fragile and I just found another bug that is related to this #144 so I am starting to wonder if this shortcut is worth it.

As Dominik raised correctly, the simple proposed fix would be to make sure that the `valid_type` is set _after_ the `dynamic` attribute, however, I find this an ugly solution. On top of that, it would indeed go against your second example. The `False` of the `Lower` would override the `True` of the `Upper` even though the former would be implicit (default) and the latter explicit. Honestly, I am not sure what the expected behavior should be here. We could add specific behavior for this attribute, but then what about the others? If the `Upper` is required but `Lower` not, should exposing make the `Upper` not required? I think this would go down a rabbit-hole. I think I prefer consistency here and just make sure that all attributes are overridden by those of the class that is exposed.

Anyway I think that one should be careful with exposing in top level namespace and not in a specific sub namespace. Especially in AiiDA process classes, where exposing in top-level will also override the `metadata` input port which is often not what one wants to do.

**Comment by sphuber** [comment]
I have opened a PR that fixes this problem. It is not an ideal solution but the best I could think of. I think the use case of someone explicitly setting `spec.inputs.some_namespace.valid_type = None` on a dynamic namespace is so rare, that it not automatically setting the `dynamic=False` as well, is not a problem.

**Comment by greschd** [comment]
> I think I prefer consistency here and just make sure that all attributes are overridden by those of the class that is exposed.

On this point I think I disagree.. there are only a few mutable namespace attributes, I think it's worth it to discuss for each what the reasonable merging behavior is.
- `required` IMO if any of the two namespaces is required, so should the result. 
- `dynamic` is actually trickier. If the "absorbing" namespace is already dynamic that should be kept (the issue here). If that is _not_ dynamic but the namespace we're exposing from I'm not sure. Maybe it should depend on whether `exclude` or `include` is used, because semantically these determine if the dynamic ports are part of the "thing to be exposed". But I'm also not sure if we handle dynamic inputs at all in `exposed_inputs`. If the user needs to anyway deal with them explicitly, might as well not set the dynamic attribute.
