### ISSUE TITLE
Optional name spaces end up in `Process.inputs` even if not explicitly passed at creation

### ISSUE THREAD

**Issue by bosonie** [aiidateam/plumpy#142]
While playing around with the siesta plugin, I noticed this behaviour.
Defining:
```
spec.input_namespace('pseudos', required="a", ..) 
```
always creates a key `pseudos` in self.inputs, independently if `a=false` or `a=true`
Here, for instance, the explicit string I get when I do print(self.inputs):
```
<AttributesFrozendict {
    'code': <Code: Remote code 'Siesta-4.0.2' on kay, pk: 2, uuid: 32a019cd-1ca9-47ac-a3f0-66bdc4d26726>,
    'structure': <StructureData: uuid: 93e4dac9-e991-4442-b00c-8e87a2d71f63 (pk: 884)>,
    'parameters': <Dict: uuid: b02f5e93-5cc1-4135-bee9-aeca0d5867f8 (pk: 885)>,
    'metadata': <AttributesFrozendict {'label': 'TestOnSiliconBulk', 'options': <AttributesFrozendict {'max_wallclock_seconds': 360, 'resources': {'num_machines': 1, 'num_mpiprocs_per_machine': 1, 'default_mpiprocs_per_machine': 20}, 'input_filename': 'aiida.fdf', 'output_filename': 'aiida.out', 'scheduler_stdout': '_scheduler-stdout.txt', 'scheduler_stderr': '_scheduler-stderr.txt', 'custom_scheduler_commands': '', 'withmpi': False, 'mpirun_extra_params': [], 'import_sys_environment': True, 'environment_variables': {}, 'prepend_text': '', 'append_text': '', 'parser_name': 'siesta.parser'}>, 'store_provenance': True, 'call_link_label': 'CALL', 'dry_run': False}>, 
    'pseudos': <AttributesFrozendict {}>
}>
```

You see the last entry is `pseudos`, that I haven't specified.
I don't know if this is a wanted feature, but for sure it is confusing for many developers as I see in the plugins lines like [this one](https://github.com/aiidateam/aiida-quantumespresso/blob/01ee430a550db789ad9c91a323408f35568e40d5/aiida_quantumespresso/utils/pseudopotential.py#L35) that are useless since pseudos is never `None`.

Personally I think that at least with `required="false"`, the `pseudos` key shouldn't be there, but maybe you have arguments against it. Also, I think the role of `required=""` for `input_namespace` is not so clear.

**Comment by bosonie** [comment]
Thanks for moving the issue on the right repository, sorry about it.
The line I put as an example is just useless because `pseudos` is never None, but an empty dictionary. The error `ValueError('neither an explicit pseudos dictionary nor a pseudo_family was specified')` is never risen. Of course the problem is caught later in line 44.

**Comment by sphuber** [comment]
> Thanks for moving the issue on the right repository, sorry about it.

No problem, it takes zero effort to move it.

> The line I put as an example is just useless because `pseudos` is never None, but an empty dictionary. The error `ValueError('neither an explicit pseudos dictionary nor a pseudo_family was specified')` is never risen. Of course the problem is caught later in line 44.

Yes, the way this function is used by the `PwBaseWorkChain` the first exception will never be hit, because it will always pass an empty dictionary, but the `validate_and_prepare_pseudos_inputs` is a generic utility function and can also be called elsewhere. There I think there _should_ be a distinction between passing `None` or `{}`. In the latter case, I think it is more appropriate to raise the exception of line 45 instead of 36. The user _did_ specify the `pseudos` argument, it just happens to be empty and therefore is invalid for the given structure (unless that structure contains exactly zero element of course, but that seems a ridiculous example).

**Comment by muhrin** [comment]
Sorry, I'm a little out of touch so this may be obvious but are there currently cases where a user would specifically want a namespace to be `required=True` but not care whether it contains any 'child' values i.e. is empty (other than perhaps that it perhaps makes the code for navigating the inputs a little easier)?  If not then I would be tempted to slowly drop support for the `required` property of namespaces and only allow this for leaves somewhat similar to the way that `git` won't allow you to commit empty folders because it is only concerend with leaves.

If this is not desirable then I would think @sphuber 's approach is a good one where the validation code is just made such that it doesn't add the empty dictionary.
