### ISSUE TITLE
Recent change from #263 breaks my workchain

### ISSUE THREAD

**Issue by danielhollas** [aiidateam/plumpy#267]
While testing my workchain with plumpy 0.21.6 for the recent boolean fix in aiidateam/plumpy#265, I noticed my workchain is broken in another way now (not present in version 0.21.5). I verified that the breakage indeed comes from the second feature introduced in 0.21.6 in aiidateam/plumpy#263.

Specifically, my workchain excepts right after submission, during the input port validation. Here's a detailed traceback. 

<details>

<summary>Traceback</summary>

```python-traceback
/opt/conda/lib/python3.9/site-packages/plumpy/ports.py in validate_ports(self, port_values, breadcrumbs)
    722         """
    723         for name, port in self._ports.items():
--> 724             validation_error = port.validate(port_values.pop(name, UNSPECIFIED), breadcrumbs)
    725             if validation_error:
    726                 return validation_error

/opt/conda/lib/python3.9/site-packages/plumpy/ports.py in validate(self, port_values, breadcrumbs)
    648 
    649         # In all other cases, validate all input ports explicitly specified in this port namespace
--> 650         validation_error = self.validate_ports(port_values, breadcrumbs_local)
    651         if validation_error:
    652             return validation_error

/opt/conda/lib/python3.9/site-packages/plumpy/ports.py in validate_ports(self, port_values, breadcrumbs)
    722         """
    723         for name, port in self._ports.items():
--> 724             validation_error = port.validate(port_values.pop(name, UNSPECIFIED), breadcrumbs)
    725             if validation_error:
    726                 return validation_error

/opt/conda/lib/python3.9/site-packages/plumpy/ports.py in validate(self, port_values, breadcrumbs)
    664                 message = self.validator(port_values_clone)  # type: ignore # pylint: disable=not-callable
    665             else:
--> 666                 message = self.validator(port_values_clone, self)  # pylint: disable=not-callable
    667             if message is not None:
    668                 assert isinstance(message, str), \

/opt/conda/lib/python3.9/site-packages/aiida/engine/processes/calcjobs/calcjob.py in validate_calc_job(inputs, ctx)
     68 
     69     code = inputs.get('code', None)
---> 70     computer_from_code = code.computer
     71     computer_from_metadata = inputs.get('metadata', {}).get('computer', None)
     72 

AttributeError: 'NoneType' object has no attribute 'computer'
```
</details>

The error is strange because it comes from calcjob input port validation for input port that should not exist. 
Specifically, in my workchain I am calling a `aiida-orca` calcjob twice in different contexts, so I am exposing the calcjob inputs into two different namespaces. However, I am excluding the `code` node to prevent duplication, and specify it manually on the workchain itself, and then manually passing it to the calcjob upon submission within the workchain.

Here's the workflow

https://github.com/ispg-group/aiidalab-ispg/blob/7bbff87cb1576d43aca8921cfd34825963f3e159/workflows/aiidalab_atmospec_workchain/__init__.py#L93

The relevant snippets

```python
    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.expose_inputs(
            OrcaBaseWorkChain, namespace="opt", exclude=["orca.structure", "orca.code"]
        )
        spec.expose_inputs(
            OrcaBaseWorkChain, namespace="exc", exclude=["orca.structure", "orca.code"]
        )
        spec.input("structure", valid_type=(StructureData, TrajectoryData))
        spec.input("code", valid_type=Code)
        .
        .
        .
   def optimize(self):
        """Optimize geometry"""
        inputs = self.exposed_inputs(
            OrcaBaseWorkChain, namespace="opt", agglomerate=False
        )
        inputs.orca.structure = self.inputs.structure
        inputs.orca.code = self.inputs.code

        calc_opt = self.submit(OrcaBaseWorkChain, **inputs)
        calc_opt.label = "optimization"
        return ToContext(calc_opt=calc_opt)
```

I believe this is a valid approach but please correct me if I am wrong.

I was quite puzzled as to why this should be broken by aiidateam/plumpy#263 because I am not explicitly using dynamic namespaces here, but I guess they are used internally. 

Here's what seems to happen. The `get_port` function that was modified in aiidateam/plumpy#263 originally returned ValueError for the code nodes that were not exposed as inputs, but that was fine because in that case the validation was skipped, see

https://github.com/aiidateam/aiida-core/blob/9de3f90a157ec7c9f99c1f17f3ca3548f6d96bba/aiida/engine/processes/calcjobs/calcjob.py#L54

But now it seems that the missing port is somehow created dynamically, but with `None` value which trips the validation code.

Note that as a somewhat separate issue, the uncought exception is particularly confusing, because the code is not guarded against the `None` value, even though it clearly permits it in just the previous line.

https://github.com/aiidateam/aiida-core/blob/9de3f90a157ec7c9f99c1f17f3ca3548f6d96bba/aiida/engine/processes/calcjobs/calcjob.py#L69

---
Not sure if this is something to be fixed in `plumpy` or `aiida-core` but I am creating the issue here since the root cause was a `plumpy` change in aiidateam/plumpy#263.

CC @sphuber 

NOTE: In my actual application, I am not calling the abovementioned workchain directly, but from within another, master workchain. Not sure if that is pertinent to the issue.

https://github.com/ispg-group/aiidalab-ispg/blob/7bbff87cb1576d43aca8921cfd34825963f3e159/workflows/aiidalab_atmospec_workchain/__init__.py#L341

**Comment by unkcpz** [comment]
Hi both, I am reviewing #268 but I am still confused about what actually happened in @danielhollas's case.  The MWE is clear shows the problem comes when the validator calls the `get_port` and creates the excluded port as dynamic. But which is such a validator in @danielhollas's process, it calls get_port explicitly?

**Comment by danielhollas** [comment]
@unkcpz the particular validator that triggered this is this CalcJob validator in aiida-core.

https://github.com/aiidateam/aiida-core/blob/9de3f90a157ec7c9f99c1f17f3ca3548f6d96bba/aiida/engine/processes/calcjobs/calcjob.py#L54

**Comment by sphuber** [comment]
The problem comes from the following "conflicting" design requirements:

* We want to allow validators that are "multi-port", since some validation rules for ports are dependent on the values for other ports
* We want ports to be exposable to allow easy composition of workchains
* When exposing, it is sometimes useful to be able to exclude certain ports so they can be added once in a different place in the namespace
* Validators on exposed port(namespace)s can be invalidated if the namespace they are contained within is exposed with certain ports excluded

So, since we know that people will likely exclude certain ports of a `CalcJob` when exposing it, we can no longer assume in the `CalcJob.validate_inputs` validator that all ports are still there when it is called. To workaround this, I changed validators to have the `PortNamespace` itself be passed in as the `ctx` argument, the last argument of the validator. This can then be used to see if the target port is still there. If it isn't, it means whoever exposed that namespace, removed that port, and so we can no longer validate it. This is why these `ctx.get_port` calls are in the validator.

Now the problem was that the change I added to make dynamic output namespaces act recursively, it would also automatically recreate the input port that was excluded, and so now the validator would think it should validate it again, but of course no value was provided and so it failed.

Hope that helps clear things up a bit

**Comment by danielhollas** [comment]
@sphuber Thank you for the plumpy PR, I am just looking at it.

Unrelated to that, did you manage to figure out why the namespace exposed from a CalcJob class is dynamic?

Also, I think it would be nice to cleanup the CalcJob validator, since I believe there is a logic error at the beginning.

```
    try:
        ctx.get_port('code')
        ctx.get_port('metadata.computer')
    except ValueError:
        # If the namespace no longer contains the `code` or `metadata.computer` ports we skip validation
        return None
```

This looks like the validator is never run, unless I provide both 'code' and 'metadata.computer', which is often redundant. I believe the validator should only be skipped if the 'code' post has been excluded, am I missing something?

**Comment by sphuber** [comment]
> Unrelated to that, did you manage to figure out why the namespace exposed from a CalcJob class is dynamic?

No, that I haven't looked at yet, since, as you pointed out, that is not the real problem. Might still have a look later, but don't think it is that important for now.

> This looks like the validator is never run, unless I provide both 'code' and 'metadata.computer', which is often redundant.

Not quite. The `ctx` is the actual `PortNamespace`, so that code is checking whether the _ports_ are still there, not the _values_ that are passed for it in the inputs. I think the check should still be there because the purpose is to make sure that if _both_ the `code` and `metadata.computer` are passed in the inputs, then they should be commensurate. But if either of them are no longer part of the input namespace, then there really isn't anything to validate.

That being said, there is still a minor inconsistency (the line doing `computer_from_code = code.computer` after we get the code knowing it may be `None`), so I might still open a PR to address it.

**Comment by unkcpz** [comment]
Thanks, both! clear to me now.

> Unrelated to that, did you manage to figure out why the namespace exposed from a CalcJob class is dynamic?

I think I have some clue one this. I try to run @sphuber's MWE and got different output as below. Then I realize I use the `Process` class from aiida-core while in the in the case above it is the Process from plumpy. The `valid_type` defined in https://github.com/aiidateam/aiida-core/blob/fce1cd6d7da2b0241830cab30a83eb5ab978a16d/aiida/engine/processes/process.py#L119 leads to the discrepancy. Afterward, the code in https://github.com/aiidateam/plumpy/blob/485b196455b848a68c5c8f8bdd2c720dcbc7bf4b/src/plumpy/ports.py#L396-L397 will make it a dynamic port.

So to me, this might be the direct root of the issue, the `expose_inputs` has no doubt to be a namespace and therefore make no sense to have a valid_type of `orm.Data` anymore.  

```
        "sub": {
            "_attrs": {
                "default": [],
                "dynamic": true,
                "help": null,
                "required": "True",
                "valid_type": "<class 'aiida.orm.nodes.data.data.Data'>"
            },
            "b": {
                "is_metadata": "False",
                "name": "b",
                "non_db": "False",
                "required": "True"
            },
            "metadata": {
                "_attrs": {
                    "default": [],
```

**Comment by unkcpz** [comment]
> Why the heck should setting a valid type automatically make the namespace dynamic??

This is asked by @danielhollas offline. @sphuber give me the reason for the initial design, can you put a quick comment here? It makes a lot of sense to me so I approve the PR for this issue.

**Comment by sphuber** [comment]
The point is that if you set a `valid_type` on a `PortNamespace`, for example, you say "this namespace accepts `str` objects", then it makes no sense to still refuse them because the namespace is not dynamic. In my mind, if you say "this namespace accepts `Data` nodes" then that clearly signals that you accept any port there as long as its type is `Data`. Otherwise, you would simply define explicit ports and set the `valid_type` on those ports.
